#!/bin/sh
# Script de Configuracion para Convertir
# el proceso as-bd en demonio, generado automaticamente

echo 'Arrancado Proceso as-BD'
exec envdir /home/ajpina/repositorio/trunk/argos-scada/config/env /bin/sh -c 'exec as-bd -h /home/ajpina/repositorio/trunk/argos-scada/config/historicos.xml -t /home/ajpina/repositorio/trunk/argos-scada/config/tags.xml -a /home/ajpina/repositorio/trunk/argos-scada/config/alarmas.xml'
